export const LOAD_USER_INFO = 'LOAD_USER_INFO';

export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const TOGGLE_EDIT_TODO = 'TOGGLE_EDIT_TODO';
export const TOGGLE_STAR_TODO = 'TOGGLE_STAR_TODO';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const UPDATE_TODO = 'UPDATE_TODO';

export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER';
export const ADD_IMAGE_PROFILE = 'ADD_IMAGE_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_REPASSWORD = 'CHANGE_REPASSWORD';
export const CHANGE_AVATAR_USER_PROFILE = 'CHANGE_AVATAR_USER_PROFILE';

export const CHANGE_USER_DATA = 'CHANGE_USER_DATA';
export const CHANGE_CONDITION = 'CHANGE_CONDITION';

// login
export const CHANGE_PHONE_OR_EMAIL = 'CHANGE_PHONE_OR_EMAIL';
export const CHANGE_LOGIN_ERROR = 'CHANGE_LOGIN_ERROR';

// sử dụng chung cho tìm trận và đặt kèo
export const CHANGE_FIND_PITCH_LOCATION = 'CHANGE_FIND_PITCH_LOCATION';
export const CHANGE_FIND_PITCH_DATE = 'CHANGE_FIND_PITCH_DATE';
export const CHANGE_FIND_PITCH_TIME = 'CHANGE_FIND_PITCH_TIME';
export const CHANGE_FIND_PITCH_TYPE_PITCH = 'CHANGE_FIND_PITCH_TYPE_PITCH';
// export const CHANGE_FIND_PITCH_TILEKEO = 'CHANGE_FIND_PITCH_TILEKEO';
// export const CHANGE_FIND_PITCH_KHU_VUC = 'CHANGE_FIND_PITCH_KHU_VUC';
// export const CHANGE_FIND_PITCH_SAN = 'CHANGE_FIND_PITCH_SAN';
export const CHANGE_MORE_REQUEST = 'CHANGE_MORE_REQUEST'; // chỉ có trong đặt kèo
export const FIND_PITCH_RESULT = 'FIND_PITCH_RESULT';
export const REMOVE_ITEM_PITCH_RESULT = 'REMOVE_ITEM_PITCH_RESULT';

export const NEW_TEAM_LOAD_FRIENDS = 'NEW_TEAM_LOAD_FRIENDS';
export const SELECT_MEMBER_FOR_NEW_TEAM = 'SELECT_MEMBER_FOR_NEW_TEAM';
export const NEW_TEAM_PROFILE = 'NEW_TEAM_PROFILE';


// team manager
export const LOAD_LIST_TEAM = 'LOAD_LIST_TEAM';
export const NEW_TEAM = 'NEW_TEAM';
export const LOAD_TEAM_DATA = 'LOAD_TEAM_DATA';
export const ACCEPT_MATCH = 'ACCEPT_MATCH';
export const REJECT_MATCH = 'REJECT_MATCH';
export const ADD_MATCH = 'ADD_MATCH';
export const REMOVE_MATCH = 'REMOVE_MATCH';
export const ACCEPT_MEMBER = 'ACCEPT_MEMBER';
export const REJECT_MEMBER = 'REJECT_MEMBER';
export const ADD_IMAGE_TEAM_PROFILE = 'ADD_IMAGE_TEAM_PROFILE';
export const CHANGE_AVATAR_TEAM_PROFILE = 'CHANGE_AVATAR_TEAM_PROFILE';

// search match
export const LOAD_MATCH_PROFILE = 'LOAD_MATCH_PROFILE';
export const LOAD_TEAM2_INFOR = 'LOAD_TEAM2_INFOR';

// search user, team
export const SEARCH = 'SEARCH';
export const SELECT_USER = 'SELECT_USER';
export const CLEAR_SELECT_USER = 'CLEAR_SELECT_USER';
export const ADD_FOLLOWING = 'ADD_FOLLOWING';
export const REMOVE_FOLLOWING = 'REMOVE_FOLLOWING';

export const SELECT_TEAM = 'SELECT_TEAM';
export const CLEAR_SELECT_TEAM = 'CLEAR_SELECT_TEAM';
export const JOIN_TEAM = 'JOIN_TEAM';
export const LEAVE_TEAM = 'LEAVE_TEAM';

// load free match
export const LOAD_FREE_MATCH = 'LOAD_FREE_MATCH';
export const CLEAR_FREE_MATCH = 'CLEAR_FREE_MATCH';
export const JOIN_FREE_MATCH = 'JOIN_FREE_MATCH';
export const LEAVE_FREE_MATCH = 'LEAVE_FREE_MATCH';
export const CREATE_FREE_MATCH = 'CREATE_FREE_MATCH';
export const DELETE_FREE_MATCH = 'DELETE_FREE_MATCH';
